forge "http://forge.puppetlabs.com"

# Modules sourced from Puppet Forge
mod "kemra102/auditd", "2.0.1"
mod "herculesteam/augeasproviders", "2.1.3"
mod "herculesteam/augeasproviders_apache", "2.0.0"
mod "herculesteam/augeasproviders_base", "2.0.1"
mod "herculesteam/augeasproviders_core", "2.1.3"
mod "herculesteam/augeasproviders_grub", "2.4.0"
mod "herculesteam/augeasproviders_mounttab", "2.0.0"
mod "herculesteam/augeasproviders_nagios", "2.0.1"
mod "herculesteam/augeasproviders_pam", "2.1.0"
mod "herculesteam/augeasproviders_postgresql", "2.0.3"
mod "herculesteam/augeasproviders_puppet", "2.1.0"
mod "herculesteam/augeasproviders_shellvar", "2.2.1"
mod "herculesteam/augeasproviders_ssh", "2.5.0"
mod "herculesteam/augeasproviders_sysctl", "2.0.2"
mod "herculesteam/augeasproviders_syslog", "2.1.1"
mod "puppetlabs/concat", "2.2.0"
mod "puppetlabs/firewall", "1.8.1"
mod "puppetlabs/inifile", "1.6.0"
mod "puppetlabs/ntp", "4.2.0"
mod "mjhas/postfix", "1.0.0"
mod "puppet/selinux", "3.0.0"
mod "puppetlabs/stdlib", "4.12.0"
mod "puppetlabs/vcsrepo", "1.4.0"
